/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profileNumber' : bigint,
  'displayName' : string,
  'avatarUrl' : string,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptContactRequest' : ActorMethod<[Principal], undefined>,
  'addPhotoToFeed' : ActorMethod<[ExternalBlob], undefined>,
  'addVideoToFeed' : ActorMethod<[ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineContactRequest' : ActorMethod<[Principal], undefined>,
  'findUserByProfileNumber' : ActorMethod<[bigint], UserProfile>,
  'findUsersByUsername' : ActorMethod<[string], Array<UserProfile>>,
  'getCallerContacts' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getPendingContactRequests' : ActorMethod<[], Array<UserProfile>>,
  'getUserPhotoFeed' : ActorMethod<[Principal], Array<ExternalBlob>>,
  'getUserPhotos' : ActorMethod<[Principal], Array<ExternalBlob>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserVideoFeed' : ActorMethod<[Principal], Array<ExternalBlob>>,
  'getUserVideos' : ActorMethod<[Principal], Array<ExternalBlob>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendContactRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'sharePhoto' : ActorMethod<[ExternalBlob], undefined>,
  'shareVideo' : ActorMethod<[ExternalBlob], undefined>,
  'updateCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
  'uploadProfilePic' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];