/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'content' : string,
  'senderUsername' : Username,
  'timestamp' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'username' : Username,
  'profileNumber' : bigint,
  'displayName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptContactRequest' : ActorMethod<[Username, Username], undefined>,
  'addPhotoToFeed' : ActorMethod<[Username, ExternalBlob], undefined>,
  'addVideoToFeed' : ActorMethod<[Username, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineContactRequest' : ActorMethod<[Username, Username], undefined>,
  'findUserByProfileNumber' : ActorMethod<[bigint], UserProfile>,
  'findUsersByUsername' : ActorMethod<[string], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[Username], Array<UserProfile>>,
  'getConversation' : ActorMethod<[Username, Username], Array<Message>>,
  'getPendingContactRequests' : ActorMethod<[Username], Array<UserProfile>>,
  'getProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPhotoFeed' : ActorMethod<[Username], Array<ExternalBlob>>,
  'getUserPhotos' : ActorMethod<[Username], Array<ExternalBlob>>,
  'getUserProfile' : ActorMethod<[Username], UserProfile>,
  'getUserVideoFeed' : ActorMethod<[Username], Array<ExternalBlob>>,
  'getUserVideos' : ActorMethod<[Username], Array<ExternalBlob>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[Username, string], boolean>,
  'registerUser' : ActorMethod<[Username, string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendContactRequest' : ActorMethod<[Username, Username], undefined>,
  'sendMessage' : ActorMethod<[Username, Username, string], undefined>,
  'sharePhoto' : ActorMethod<[Username, ExternalBlob], undefined>,
  'shareVideo' : ActorMethod<[Username, ExternalBlob], undefined>,
  'updateUserProfile' : ActorMethod<[Username, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];